### PR TITLE
Support 1.13.x - 1.18.x [Maybe]

### PR DESCRIPTION
**Pull request by VoChiDanh**
If you are not familiar with maven, you may not need to merge :thinking:

### CODE REVIEW

**Comment by ColinGrime** [comment]
I'm not very familiar with Maven, so I'll keep using Gradle.

But I do need to update the "api-version" in the plugin.yml file.  I believe changing that is all that's needed.

I'll test it on 1.13 shortly and update the repo if it works.

**Comment by ColinGrime** [comment]
Scratch that.  Java 17 will prevent the server from running on lower versions anyways.  Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.

**Comment by VoChiDanh** [comment]
> I'm not very familiar with Maven, so I'll keep using Gradle.
> 
> But I do need to update the "api-version" in the plugin.yml file. I believe changing that is all that's needed.
> 
> I'll test it on 1.13 shortly and update the repo if it works.

Some method can use in 1.18 but lower version can't


> Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.

If we use paper, we can use 1.13.x with java 17

**Comment by ColinGrime** [comment]
> > Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.
> 
> If we use paper, we can use 1.13.x with java 17

How's that?  I thought earlier versions can only support up to a certain Java version (<17).

**Comment by VoChiDanh** [comment]
> > > Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.
> > 
> > 
> > If we use paper, we can use 1.13.x with java 17
> 
> How's that? I thought earlier versions can only support up to a certain Java version (<17).

if you use paper, add `DPaper.IgnoreJavaVersion=true` to cmd to start server so you can use any version with java 17

**Comment by ColinGrime** [comment]
> > > > Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.
> > > 
> > > 
> > > If we use paper, we can use 1.13.x with java 17
> > 
> > 
> > How's that? I thought earlier versions can only support up to a certain Java version (<17).
> 
> if you use paper, add `DPaper.IgnoreJavaVersion=true` to cmd to start server so you can use any version with java 17

Sure enough, it worked!  I had no idea that was an option.
I suppose it's worth it to change the api-version then, so I just pushed that change.

Thanks for enlightening me on this neat feature!

**Comment by VoChiDanh** [comment]
> > > > > Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.
> > > > 
> > > > 
> > > > If we use paper, we can use 1.13.x with java 17
> > > 
> > > 
> > > How's that? I thought earlier versions can only support up to a certain Java version (<17).
> > 
> > 
> > if you use paper, add `DPaper.IgnoreJavaVersion=true` to cmd to start server so you can use any version with java 17
> 
> Sure enough, it worked! I had no idea that was an option. I suppose it's worth it to change the api-version then, so I just pushed that change.
> 
> Thanks for enlightening me on this neat feature!

but some method can't use in older version, did you tested?

**Comment by ColinGrime** [comment]
> > > > > > Scratch that. Java 17 will prevent the server from running on lower versions anyways. Yet I need Java 17 in order to hook into FAWE, so the plugin is compiled in that version.
> > > > > 
> > > > > 
> > > > > If we use paper, we can use 1.13.x with java 17
> > > > 
> > > > 
> > > > How's that? I thought earlier versions can only support up to a certain Java version (<17).
> > > 
> > > 
> > > if you use paper, add `DPaper.IgnoreJavaVersion=true` to cmd to start server so you can use any version with java 17
> > 
> > 
> > Sure enough, it worked! I had no idea that was an option. I suppose it's worth it to change the api-version then, so I just pushed that change.
> > Thanks for enlightening me on this neat feature!
> 
> but some method can't use in older version, did you tested?

Ah, that's my bad.  I was trying out different versions to see if anything below 1.18 would work, and so I ended up testing it on 1.16.5, not 1.13.

There seem to be quite a few errors all involving Java 17 being unsupported.  Is there a way to compile the plugin in Java 17, but allow 1.13 users to use the plugin?  I'm used to using Java 8 but only switched for FAWE compatibility.

**Comment by VoChiDanh** [comment]
> > > > > > > 
> 
> Ah, that's my bad. I was trying out different versions to see if anything below 1.18 would work, and so I ended up testing it on 1.16.5, not 1.13.
> 
> There seem to be quite a few errors all involving Java 17 being unsupported. Is there a way to compile the plugin in Java 17, but allow 1.13 users to use the plugin? I'm used to using Java 8 but only switched for FAWE compatibility.

Maybe SkyMines  need java 17 and only support Paper or Paper fork so user can use SkyMines with 1.13.x - 1.18.x, I was update my fork to compatible with 1.13.x - 1.18.x without error in code but some error in server: https://github.com/VoChiDanh/SkyMines/issues/1 :thinking:

**Comment by VoChiDanh** [comment]
if you want to turn java 8, you need recode some class command and maybe replace FAWE with WorldEdit :thinking:

**Comment by ColinGrime** [comment]
> Maybe SkyMines need java 17 and only support Paper or Paper fork so user can use SkyMines with 1.13.x - 1.18.x, I was update my fork to compatible with 1.13.x - 1.18.x without error in code but some error in server: [VoChiDanh#1](https://github.com/VoChiDanh/SkyMines/issues/1) 🤔

Oops, this time I was using Java 18 hence all the unsupported errors.  I'll see if I can find out what's happening to result in the server error.

> if you want to turn java 8, you need recode some class command and maybe replace FAWE with WorldEdit 🤔

I don't have a huge complaint about switching versions.  Plus, it was never my intention to support all versions to begin with, and since Java 17 is already required for all future versions, I thought it was fine.

**Comment by VoChiDanh** [comment]
> > Maybe SkyMines need java 17 and only support Paper or Paper fork so user can use SkyMines with 1.13.x - 1.18.x, I was update my fork to compatible with 1.13.x - 1.18.x without error in code but some error in server: [VoChiDanh#1](https://github.com/VoChiDanh/SkyMines/issues/1) thinking
> 
> Oops, this time I was using Java 18 hence all the unsupported errors. I'll see if I can find out what's happening to result in the server error.
> 
> > if you want to turn java 8, you need recode some class command and maybe replace FAWE with WorldEdit thinking
> 
> I don't have a huge complaint about switching versions. Plus, it was never my intention to support all versions to begin with, and since Java 17 is already required for all future versions, I thought it was fine.

You can download artifact: https://github.com/VoChiDanh/SkyMines/actions/runs/2187498868 and test it on any version, if they no give error. Maybe it done about update :smile:

**Comment by VoChiDanh** [comment]
or you can test your version too

**Comment by ColinGrime** [comment]
So it seems that even using Java 17 on Paper 1.13.2 results in unsupported version 61 errors (I tried it using your version).  Which is odd because version 61 is definitely Java 17.

Despite that, I had a look at your error and it seems to be coming from the main menu.  This actually makes a lot of sense since I used a respawn anchor as the reset icon (1.16).  I did a quick null check which makes invalid items become STONE:

https://github.com/ColinGrime/SkyMines/releases/tag/v1.2.2

Tell me if this fixes your issue!

**Comment by VoChiDanh** [comment]
> So it seems that even using Java 17 on Paper 1.13.2 results in unsupported version 61 errors (I tried it using your version). Which is odd because version 61 is definitely Java 17.
> 
> Despite that, I had a look at your error and it seems to be coming from the main menu. This actually makes a lot of sense since I used a respawn anchor as the reset icon (1.16). I did a quick null check which makes invalid items become STONE:
> 
> https://github.com/ColinGrime/SkyMines/releases/tag/v1.2.2
> 
> Tell me if this fixes your issue!

it's work, thanks

**Pull request closed without merging**
